export const impactRegistryAbi = [
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"id","type":"uint256"},{"indexed":true,"internalType":"address","name":"user","type":"address"},{"indexed":false,"internalType":"string","name":"actionType","type":"string"},{"indexed":false,"internalType":"string","name":"metadataURI","type":"string"}],"name":"ImpactSubmitted","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"id","type":"uint256"},{"indexed":false,"internalType":"uint16","name":"aiScore","type":"uint16"},{"indexed":false,"internalType":"uint256","name":"reward","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"tokenIdMinted","type":"uint256"}],"name":"ImpactVerified","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"nft","type":"address"}],"name":"NFTContractSet","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},
  {"inputs":[{"internalType":"uint256","name":"id","type":"uint256"}],"name":"getImpact","outputs":[{"components":[{"internalType":"address","name":"user","type":"address"},{"internalType":"string","name":"actionType","type":"string"},{"internalType":"string","name":"metadataURI","type":"string"},{"internalType":"uint64","name":"timestamp","type":"uint64"},{"internalType":"uint16","name":"aiScore","type":"uint16"},{"internalType":"uint256","name":"reward","type":"uint256"},{"internalType":"bool","name":"verified","type":"bool"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"internalType":"struct ImpactRegistry.Impact","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"impacts","outputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"string","name":"actionType","type":"string"},{"internalType":"string","name":"metadataURI","type":"string"},{"internalType":"uint64","name":"timestamp","type":"uint64"},{"internalType":"uint16","name":"aiScore","type":"uint16"},{"internalType":"uint256","name":"reward","type":"uint256"},{"internalType":"bool","name":"verified","type":"bool"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"nextId","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"nft","outputs":[{"internalType":"contract IImpactNFT","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"nftContract","type":"address"}],"name":"setNFTContract","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"string","name":"actionType","type":"string"},{"internalType":"string","name":"metadataURI","type":"string"}],"name":"submitImpact","outputs":[{"internalType":"uint256","name":"id","type":"uint256"}],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"uint16","name":"aiScore","type":"uint16"},{"internalType":"uint256","name":"reward","type":"uint256"},{"internalType":"bool","name":"mintNFT","type":"bool"}],"name":"verifyImpact","outputs":[],"stateMutability":"nonpayable","type":"function"}
] as const;

export type ImpactRegistryAbi = typeof impactRegistryAbi;
